version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s | %(levelname)-8s | %(name)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    class: src.monitoring.logger.JSONFormatter
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: standard
    filename: logs/datapulse.log
loggers:
  src:
    level: INFO
    handlers: [console]
root:
  level: WARNING
  handlers: [console]
